### ISSUE TITLE
Violation of Binance's Terms of Use

### ISSUE THREAD

**Issue by flxai** [Superalgos/Superalgos#1019]
## Context

**Operating System:** Linux

**Software version:** today's master branch

**Workspace version:** default Workspace.json (Getting Started Guide)

**Reproducible:** the issue may be reproduced.

### 1. Explain what the problem seems to be.

[Binance's Terms of Use (ToS)](https://www.binance.com/en/terms) state that 

> [III.1.b.iv] Without written consent from Binance, the following commercial uses of Binance data are prohibited:
> 1) Trading services that make use of Binance quotes or market bulletin board information.
> 2) Data feeding or streaming services that make use of any market data of Binance.
> 3) Any other websites/apps/services that charge for or otherwise profit from (including through advertising or referral fees) market data obtained from Binance.

I think that this legal statement is mostly unaffected by regional context and therefore can be interpreted as applicable worldwide.
Now using the Getting Started Guide, the user is guided to activate a scraper that does apparently violate these ToS.

### 2. Clearly explain what you wish to accomplish.

I want to use Superalgos without violating another companies (e.g. Binance's ToS).

### 3. Explain, step by step, what you've done to achieve the goal. The Team will follow these steps to reproduce the issue, so be precise.

I followed the getting started guide as explained in the `README.md`.

### 4. Explain what is the result you expect from your actions.

Data downloaded from Binance without violating their ToS.

### 5. Explain what happens instead of the expected results.

I appear to violate Binance's ToS by following the steps of the Getting Started Tutorial.

### 6. Explain what errors you have found on-screen, on the browser console application, or in the ```Log-Files``` folder.

IANAL so is there actually a violation of Binance's ToS happening?
Can I use the software without violating Binance's (or some other third party's) ToS?
It appears to me that the **commercial uses of Binance data** as quoted above is given since this tries to activate not only a scraper but also a trading bot as a later goal.

**Comment by Luis-Fernando-Molina** [comment]
Hello Felix. The Software is an open source project for free, not a commercial software. There are no fees and no one is charging anyone for anything, so there is no violation of any ToS, from Binance or any other exchange.  The whole purpose for Binance or any other exchange to have a public API is for it's users to use a software and automate their trading, for that you need to download their data to backtest. This is exactly the use case for which they all have an API, and they are happy to let anyone trade autonomously since they charge you and others fees with every trade you make.

**Comment by flxai** [comment]
Thanks for clearing it up.
