### ISSUE TITLE
Provide a way to know if all data sets are up to date

### ISSUE THREAD

**Issue by julian-molina** [Superalgos/Superalgos#115]
**Basic users** need to be able to know if all (active) data sets are up to date before running a live trading session. 

Maybe a date progress displayed under the task manager, indicating the date of the process that is further back in the past?

**Comment by bmcd77** [comment]
I've been testing superalgos and after 4 new setups I've only seen a date appear under Bot Paula the very first time (ref : described on the how to update your datasets before trading live page and how to know if you're up to date). 

So I've not been sure despite having copied over the 3Gig DataStorage and run for 8 Hrs whether my datasets have been up to date. I watched the console messages but wasn't completely sure either. I incurred errors when attempting to start the live trading session probably indicating my data was not up to date so this is a great suggestion. 

It would seem to make sense to link the display item possibly to the master dataset task because that is keeping the files up to date.  An upvote from me for this suggestion.

**Comment by Luis-Fernando-Molina** [comment]
I will try to include this on the next release. In the meantime let me give you a few tips for knowing when you are up-to-date:

![image](https://user-images.githubusercontent.com/9479367/71982267-58e78200-3224-11ea-9877-9d70b251dbff.png)

1. Go to the charts and point with the mouse at the last candle. If the date of the Time Scale is not the current GMT datetime, then it is not up to date. While running the task for Master bots, the chart should update automatically as new data arrives.

2. The reason you have only seen the date below Paula, it is because Paula is the only 2nd generation bots of that set. All the others are still 1st generation and have not been ported yet. So for now that is normal. (With 2nd generation I mean that the bots are created within the UI, in contrast to 1st Generation which are created by coding them in javascript.

3. If Paula's date is your current date, then that also means everything is synchronized. Paula is the last dependency among all the others, which means that if Paula is up-to-date, all the others MUST be.

4. When you see your console like this, with all the bots running, it is a very good sign that there is no problem there. Specially if the number highlighted is above 30. That number changes every minute, and represents the times each bot ran. For syncing a few days of trades it usually takes less than 20 minutes, depending on the bandwidth and hardware. If you are very far behind, extrapolate that. 

![image](https://user-images.githubusercontent.com/9479367/71982929-f4c5bd80-3225-11ea-9ab2-3b29da7b3a69.png)

5. Another way to know what is missing is looking at the folders at your disk. If there are some days missing it means it is still working on syncing. In the picture all the days are already there in my case. Be aware that in the current version it starts grabbing the trades from present time and goes back slowly until reaching the point were it left the last time it ran.

![image](https://user-images.githubusercontent.com/9479367/71983114-5dad3580-3226-11ea-90d1-69aeef1bbd42.png)

Hope this helps in the meantime while I improve this area.

**Comment by julian-molina** [comment]
@bmcd77 feel free to message me on Telegram if you ever get stuck or need help...

**Comment by Luis-Fernando-Molina** [comment]
With the new features of automatic scales, we somehow fix this, since now you can see at the chart all the data available.
