### ISSUE TITLE
Feature: Harden Icon Loading 

### ISSUE THREAD

**Issue by harrellbm** [Superalgos/Superalgos#1703]
Harden icon loading in tutorials and potentially system wide.

Goal: make it possible to move icons around within the icons folders within a project and the system still finds it

Possible implementations:

load all images into an array and walk it if an icon cannot be found

use node-findit to search the icons directory for the missing icon

**Comment by Luis-Fernando-Molina** [comment]
This is a good idea, in fact in great part of the system it works just like that. 

It seems that the weak part was the implementation of icons in tutorials, that instead of getting them from the pre-laded icons already in memory, they request them to the Client via http, and now that icons have moved into folders, it created a mess. 

You just need to get them in the same way they are fetched from memory for instance when a node is displayed at the designer.

**Comment by harrellbm** [comment]
Sweet! That will be a much easier fix than I anticipated 😂
