### ISSUE TITLE
Decouple Education Project

### ISSUE THREAD

**Issue by harrellbm** [Superalgos/Superalgos#1704]
Decouple education project from foundations project

Make the education project as modular as possible. Still relying on the core utility and functions libraries of the foundations project but moving any unique code used only for docs and tutorials to education project.

The Education Project will become the engine to run tutorials and docs for the other projects

**Comment by Luis-Fernando-Molina** [comment]
> Decouple education project from foundations project

This is good, the decoupling is probably not complete yet.
 
> Make the education project as modular as possible. Still relying on the core utility and functions libraries of the foundations project but moving any unique code used only for docs and tutorials to education project.

Also good.

> Also possibly store all docs within education project pulling them out of the other projects

This would not be good, because each project should have its own documentation, tutorials and so on. One of the reasons for this is that when someone takes responsibility for the project, this includes it's documentation, and once we allow from the Governance System to assign project leaders with auto git-merge, that should include all the project's assets, including it's docs and tutorials.

**Comment by harrellbm** [comment]
Sounds good will edit issue 👍🏼

**Comment by harrellbm** [comment]
Nodes that have been decoupled:

- Docs Space
- Docs Space Settings 
- Docs Space Style
- Tutorial
- Tutorial Topic
- Tutorial Step

**Comment by harrellbm** [comment]
Utilities that need decoupled:

- [ ] Tutorial.js
