### ISSUE TITLE
Feature: Standalone Documentation Website

### ISSUE THREAD

**Issue by harrellbm** [Superalgos/Superalgos#1718]
Standalone website to view Superalgos documentation.

**Comment by Luis-Fernando-Molina** [comment]
Let me know if you need directions once you start doing this.

**Comment by harrellbm** [comment]
Forwarded from Julian: 
The way the docs are built, with a style per paragraph, should be easy to translate to simple HTML. Each paragraph on a <div> tag, with a specific CSS class.

The collection of paragraphs can be inserted on the website's template, inside <section> tags.

**Comment by ssplatt** [comment]
It's been a while since I've seen this discussed but I think this project should get some attention soon. I think a good solution may be to use Github Pages to serve the docs right from the main repo in a /docs folder or a new repo that separates the docs from the rest of the code (which may help reduce the collateral damage in PRs). We can use Pandoc (https://pandoc.org/) to convert just about any file type over to Jekyll or Markdown. There are other solutions like readthedocs (https://readthedocs.org/) and gitbook (https://www.gitbook.com/) which will provide a free platform for docs which can be fed from a github repo.

I know part of the discussion was to host the docs under the main superalgos.org domain and not a subdomain, like docs.superalgos.org, but the research I've done does not necessarily show that hosting under docs.superalgos.org is worse for SSO.

**Comment by julian-molina** [comment]
Just bear in mind that the goal is not to remove the Docs from within the app. The Docs interact with the app in MANY different ways. The goal is to set up a separate resource, pulling pages from the in-app docs, which will always be the up-to-date version.

**Comment by harrellbm** [comment]
Addressed by @Awhiteweb
