### ISSUE TITLE
Design Space ability to move hierarchies when zoom out

### ISSUE THREAD

**Issue by 9808us** [Superalgos/Superalgos#218]
See attached image

![image](https://user-images.githubusercontent.com/38046064/81257607-f7012280-9033-11ea-9f1b-66ed46f129bf.png)

**Comment by Luis-Fernando-Molina** [comment]
Challenging, but possible. Makes sense.

**Comment by Luis-Fernando-Molina** [comment]
In Beta 6 you can not move it from the Map, but a change was made so that Hagiarchies do not need that their children be pinned. That means that you can move only the hierarchy head node by dragging or with the keyboard without any further steps of moving their children. This is the closest thing I can make for now regarding this.
