### ISSUE TITLE
RSI bad behaviour

### ISSUE THREAD

**Issue by 9808us** [Superalgos/Superalgos#226]
RSI reports wrong values

See screenshots from Tradingview and Superalgos

Time Frame 15min for both

![image](https://user-images.githubusercontent.com/38046064/81750746-5e90f500-94ae-11ea-8f71-1e9dbac19797.png)

![image](https://user-images.githubusercontent.com/38046064/81751060-fc84bf80-94ae-11ea-8d0d-32239e41ec0b.png)

Also some candles before RSI 0.00 are wrong, API problems retrieving correct data?

**Comment by Luis-Fernando-Molina** [comment]
That pattern of flat candles is what we usually see when the exchange is out (for maintenance for instance) and no trades happens during that period of time. In fact that is kind of corroborated by the fact that the same pattern appears at the BTC/USDT market during the same period of time:

![image](https://user-images.githubusercontent.com/9479367/82234566-de491480-9931-11ea-8d29-fa54234bedc2.png)

How did Trading View got non empty candles during that time is unknown to me. Maybe they are querying trades instead of candles from the exchange, and building candles out of trades (produced by who know who), or maybe is something else. In any case the information that Binance provides to the general public seems to be no candles there. Regarding the RSI anomaly there, it is very likely to be related to the group of empty candles before it. I did not check that deeply, if it appears again somewhere else I will.
