### ISSUE TITLE
Modifications in WHB strategy disappeared when refresh

### ISSUE THREAD

**Issue by EduRemix** [Superalgos/Superalgos#241]
In the "Binance - BBTB - WHB" workspace found in the repo, I saved it with another name, I made some modifications to the telegram announcements and some conditions of the WHB strategy and I saved the changes with CTRL + SHIFT + S. When I refreshed the browser the modifications I made disappeared. It is proposed that changes made to default strategies can be saved.
<em>Note: The changes I made to the BBTB strategy were saved. In this case it worked according to expectations.</em>

**Comment by Luis-Fernando-Molina** [comment]
Could you reproduce this ? did it happen again?
Currently since the moment you start using a default workspace it is saved at the My Workspaces folder and becomes your version of that workspace.

**Comment by EduRemix** [comment]
I have installed the recent release # 5, as explained in the official documentation: https://docs.superalgos.org/suite-upgrading-your-existing-instalation.html

Then I have tried different ways and the same thing that I have explained always happens.

Video 1 shows the Default Workspace as soon as I run the new release, then I go to the WHB strategy and remove the trigger off node, save the changes and refresh the page.
![1-Editing Workspace and saving changes](https://user-images.githubusercontent.com/54202149/84251045-185e9e00-ab0d-11ea-9d1d-f91fe3252be6.gif)

In video 2 I go back to WHB and what I have eliminated reappears.
![2-Workspace after reload](https://user-images.githubusercontent.com/54202149/84250302-295adf80-ab0c-11ea-8040-825055e6bfea.gif)

I have tried saving the workspace with another name and the same thing happens.
I have tried the "Binance-WHB-BBTB" workspace that brings the soft by default and the same thing happens.

**NOTES**: 
1) BBTB does not appear in the default worskpace.
2) BBTB appears in the "Binance-WHB-BBTB" workspace.

**Comment by julian-molina** [comment]
This behavior is to be expected as per the current software design. Trading systems shipping with the software are loaded by the frontend from the ```Trading-Systems``` folder. Modifications made to those hierarchies (the same goes for Data Mines) are not saved in the Workspace file.

The confusion arises because the BBTB Trading System has not been added to the Workspace in the official manner. Instead, it has been incorporated in the Workspace temporarily. That is why you may save modifications on this trading system by saving the workspace.

If you wish to save modifications in WHB, you may do either of the following:

1. Clone WHB, so that the clone lives within the workspace as a User trading system. modify the clone, not the original.

2. Modify the original, back it up, and replace the original file in ```Trading-Systems``` with your back up.

**Comment by EduRemix** [comment]
It's very clear now, thanks!
