### ISSUE TITLE
Doesn't run on Mac OS 11.4 on M1

### ISSUE THREAD

**Issue by joeyfigaro** [Superalgos/Superalgos#2748]
## Before you open an issue

There are two requirements to open an issue:

1. ~You must first follow the [Troubleshooting Guide](https://docs.superalgos.org/suite-how-to-troubleshoot-an-issue.html)~
Looks like this just gets redirected to [superalgos.org](https://superalgos.org)

2. ~If your issue hasn't been resolved by following the Troubleshooting Guide, then follow the guide on [How to Report an Issue](https://docs.superalgos.org/suite-how-to-report-an-issue.html).~
Same issue with this link–just redirects to superalgos.org.

## Context

**Operating System:** MacOS

**Software version:** both `today's master branch`, `today's develop branch `

**Workspace version:** None–the bug is that the application fails critically on first launch.

**Reproducible:** the issue may be reproduced.

### 1. Explain what the problem seems to be.

After mounting the dmg, moving the application, and launching it it fails with `Superalgos is damaged and can't be opened. You should move it to the Trash.`

[https://joeysharesthings.com/xD2bq9](https://joeysharesthings.com/xD2bq9)

### 2. Clearly explain what you wish to accomplish.

Launch the app

### 3. Explain, step by step, what you've done to achieve the goal. The Team will follow these steps to reproduce the issue, so be precise.

- Downloaded both the nightly and stable releases from github releases
- Mount the dmg
- Move the application into `/Applications`
- Run it

### 4. Explain what is the result you expect from your actions.

The app to run

### 5. Explain what happens instead of the expected results.

The app fails critically on launch with the message above

### 6. Explain what errors you have found on-screen, on the browser console application, or in the ```Log-Files``` folder.

`Superalgos is damaged and can't be opened. You should move it to the Trash.`

## Attach a video reproducing the issue

N/A

## Attach relevant log files and error screenshots

[https://joeysharesthings.com/xD2bq9](https://joeysharesthings.com/xD2bq9)

## Attach you custom workspace if any

N/A

**Comment by superharoun** [comment]
Hi @joeyfigaro, don't know if you still have the issue ?

This happens because the binary is not signed (i am not technical).
On my end it worked on my M1, on past binaries generated, by doing in the terminal, in the folder where you put the binary : 
`xattr -rd com.apple.quarantine Superalgos.app`
Then launch the app.

This was previously mentioned here : https://github.com/Superalgos/Superalgos#mac-os-install but i see it is not the case any more, so maybe you should first try : 
`NOTE The application is not signed. To be able to run you have to permit it in System Preferences > Security & Privacy > General > Open Anyway.`

Please let us know if those options work to know if the readme needs to be amended.

Regards
Haroun

**Comment by superharoun** [comment]
Hi @joeyfigaro , hope all is well ! Did you give a try to these proposals ?

**Comment by superharoun** [comment]
#3068

**Comment by superharoun** [comment]
To close
