### ISSUE TITLE
Docs from the troubleshooting guide are missing

### ISSUE THREAD

**Issue by slow-crypto** [Superalgos/Superalgos#3275]
## Before you open an issue

the following two documents are missing:

1. [Troubleshooting Guide](https://docs.superalgos.org/suite-how-to-troubleshoot-an-issue.html)

2. [How to Report an Issue](https://docs.superalgos.org/suite-how-to-report-an-issue.html).

## Context

*Complete and adjust the contents leaving the information that fits your case and deleting the information that doesn't.*

**Operating System:** | MacOs 
**Software version:**  today's develop branch 

**Workspace version:** default Workspace.json 

**Reproducible:** the issue may be reproduced.

### 1. Explain what the problem seems to be.
Copying the above links and pasting them into the browser, I am redirected to the index page from superalgos.org
Searching the document page from within the app in the developerbranch  there were no search results

Type your explanation here.

I was looking for the trouble shooting guide and couldnt find it on the website and not within the app.

**Comment by gustavohcorradi** [comment]
Dear Martin: 
this is an open source project and is constantly in development..there is plenty of information for each new user to fully understand it ( the whole web site + the blog in medium + the in app docs and books) and also get help (i.e. the support telegram group).
So, it is not mandatory to have a different ´troubleshooting guide´ ...because all that published info IS itself a troubleshooting guide..Superalgos is complex and very specifically technical..so, it needs that new users do their best first reading all the info available and turning to the existing channels for help...
Github issues should be used only for reporting technical problems discovered..like for e.g. that of the ´signature hash´ that you mentioned in your previous issue.
Thanks for understanding!

**Comment by julian-molina** [comment]
Thanks for pointing that out @slow-crypto. The links in the templates where pointing to a site that no longer exists. I have removed the links. Please find the equivalent info in the built-in Docs by searching for the title string.

**Comment by gustavohcorradi** [comment]
thanks @julian-molina for clearing this out !
