### ISSUE TITLE
Monitoring https://whale-alert.io/ with machine learning

### ISSUE THREAD

**Issue by MojoMoe** [Superalgos/Superalgos#337]
Would it be possible to monitor the movement of huge sums so as to check what this does to the prices of all or some of the crypto coins and create good indicators out of that data? https://whale-alert.io/ provides API for free if used for personal use, in this case it would be I suppose.

**Comment by Luis-Fernando-Molina** [comment]
As of today, it would be possible with some NodeJS coding. You could code a Sensor Bot to fetch information from that API, and run it like a task every minute if you wish, and the info gathered could then be plotted, fed to indicators or directly to trading strategies. 

In the future I hope to create a way to map APIs at the Designer so that less coding would be required for accessing any API  out there.
