### ISSUE TITLE
Refactor httpInterface.js to use a proper web framework

### ISSUE THREAD

**Issue by NAmorim** [Superalgos/Superalgos#3541]

**Comment by isysd-mirror** [comment]
I don't think a framework per-se would be helpful. What is the expected benefit? Code organization?

I agree re-factoring is needed, but we should carefully consider which, if any, framework to implement. Frankly, I find it easier to use the core NodeJS libs. Since we're controlling both server and client sides, everyone could easily use HTTP2, push notifications, and other awesome advancements.

**Comment by NAmorim** [comment]
I agree that a framework is not a silver bullet by itself. 
I think that exploring this option might be better in the long run because of maintainability and specially security issues. Have the "specialists" focus on that http management part so that we focus in the product.

My first choice would be the usual suspect Express. But I'm not knowledgeable in the node ecosystem, so I would need to dig further.
