### ISSUE TITLE
3. Tutorial Step - Client "Next" Button does not work

### ISSUE THREAD

**Issue by mARTin-B78** [Superalgos/Superalgos#3554]
Hitting "Next" leads to the same page you are on.. so you can not go to the chapter "4. Tutorial Step - Collection of Servers"

**Comment by BastianMuc** [comment]
I assume you are referring to the Developers Intro tutorial?
If so: Seems to be caused by a duplicate page. We'd need to delete the duplicate and repaginate. This will though create merge conflicts with ongoing translations (and I assume that's what you're currently doing).

Let me know when you're finished and your translations are merged - we can then double-check with the wider group before we execute on fixing this.

**Comment by mARTin-B78** [comment]
I have run the app.contribute command and created a PR
https://github.com/Superalgos/Superalgos/pull/3555
