### ISSUE TITLE
Rework Indicators/Data-mines

### ISSUE THREAD

**Issue by BlaaSwe** [Superalgos/Superalgos#3716]
Firstly, I know little about the feasibility nor technical challenges associated with this proposed change. 

**The problem:**
For new users to easily oriented themselves they need to understand many aspects before appreciating Superalgos capabilities.
It is hard to understand the different nodes and what they do and in which order things go, and where... A normal user wants to fast open a market and add indicators to try a strategy. 

**Proposal:**
Remove the need to add a data mine node from the plugin section, instead let the user from the `Market Data Tasks` create their own data-mine setup. The various indicators could be added from the` Task Manager` in a categorical way (in similiar fashion as add tasks to the `LAN Network Node`) then followed by a list (as with `Add Specified Plugin Data Mine`, but with indicators instead) to choose from. The Data Mines could still be used, as to not download duplicate datasets, just the references and locations are handled in the background.

**Concept flow:**
1) Add new custom `Data Mine Tasks`

2) Add new `Task Manager`
![image](https://user-images.githubusercontent.com/93773753/151535654-b05326d7-4d3d-4ca7-a80c-cbabf4997682.png)

3) Choose categories to filter indicators 
![image](https://user-images.githubusercontent.com/93773753/151535619-02b5f8f3-71e9-4c85-a441-2bf092fa0214.png)

4) Choose indicator from list
![image](https://user-images.githubusercontent.com/93773753/151535673-5e3084b1-9db2-4f1c-a287-8e54d79702a4.png)

**Comment by Luis-Fernando-Molina** [comment]
The current way of doing it is the result of the fact that everything is general purpose and there is still no specialized functionality for Data Mining, like a side panel where you can explore all the ones that exist or create a new one from there. There could also be a System Menu that could allow you to load Data Mines from there. Maybe @whtv can help you with that if you like the idea.

**Comment by whtv** [comment]
This might be convenient, but it is illogical to add indicators from a task manager. Instead, we should have a way to add a specified indicator to a data mine. You can create an empty data mine from the Data-Mining project node. What I propose is a menu item in the data mine to add a specified indicator, like you suggest in your last mock-up. It shouldn’t be too hard to extract a list of indicators from the `indicatorBots` property of each JSON file in Plugins/Data-Mining/Data-Mines.

Then, the work flow would be like this:
1. Create new data mine from the Data-Mining project node.
2. Add the indicators you want.
3. Add new data mine tasks, reference the new data mine and use “add all tasks”.

**Comment by whtv** [comment]
Ok, so after actually implementing a new action to add a specified indicator bot to a data mine, I came to the conclusion that this doesn’t make all that much sense after all. Indicators depend on each other, and you will need to know beforehand or figure out afterwards on which other indicators your new indicator depends on. Then you will need to add those dependency indicators and create your references accordingly.

It kind of makes sense that indicators are part of a trading mine and not standalone plugins. That’s not to say it wouldn’t be preferable for them to be plugins that define their own dependencies of course …

Btw, there are 135 indicators in plugin data mines at this point.

@Luis-Fernando-Molina @BlaaSwe let me know if you think there’s any use in that new action for data mines or if I should throw it away.

**Comment by whtv** [comment]
Actually, the dependency issue also exists between data mines. Most, if not all of the plugin data mines will depend on the Candles data mine, and those dependencies are nowhere taken care of when a plugin data mine is loaded, as far as I can see.

**Comment by Luis-Fernando-Molina** [comment]
If the problem is the one stated:

"Users would like to add certain indicators to their strategy without going through the complexity of adding them manually as plugins and sorting out their dependencies".

Then what I would do is the following:

I would code a new Space at the Data Mining project, implemented as a right tab, similar to Gov, or Docs and I would call it Indicators.

I would create a list of indicators based on reading all the Data Mines plugins in a table like this:

Loaded at Workspace (checkbox) | Indicator Name | Data Mine | Depends On (indicator / data mine)

There are already examples of how to easily create tables there.

Users should be able to check and uncheck indicators from the list. 

Then there would be 3 possible solutions:

1) Load the Data Mines that contains the indicators the user wants. This would be sub optimal, because it would load many, many definitions that are not actually needed, but it could work anyways. The only trade off here would be many info at the workspace not actually needed.

Another trade off is that a Market Install would install data tasks for all indicators available at all data mines, not only the ones actually needed.

2) Programmatically create a Data Mine that will live inside the workspace (and not be a plugin), adding to that Data Mine the Indicator bots definitions taken from the plugin data mines.

This is harder to pull out, since the code should also port the dependencies of the chosen indicators recursively (dependencies of dependencies). 

It will also have to take into account the plotters that apply to the selected indicators. 

It will also have to take into account the possible naming conflicts of indicators from different data mines.

In this scenario, the user would have his custom data mine auto generated and ready to use, but will have some trade offs:

a. The code of conditions and formulas would depend on his custom data mine and would not be useful for sharing.
b. He would have forked out from any improvements of the data mines plugins, though he might re run the procedure and get up-to-date. 
 
3) A third way of doing this would be making a clone of the needed plugins and strip them of all the indicators not selected on the list. The user would end up with a copy of the needed plugins living at his workspace, not as plugins anymore. This would avoid the trade off of point 1 and 2.

This idea is the most powerful because then an Install Market run will install the Data Mining tasks and charts elements actually needed, and anything else.

If the user would like to add or remove indicators from the list, the procedure would be or it might automatically include a Uninstall Market first to clean all, add or remove indicators from the list, and an Install Market to make all the connections again of tasks and charts elements.

Also this point 3 is easier to implement than 2. While removing the unneeded Indicators and Plotters dependencies need to be accounted for and everything should be fine.

Point 3 in my view is the solution to the stated problem.

**Comment by whtv** [comment]
Yes, 3 sounds good. Although it will still have the trade-off 2.b, right?

I guess I’ll park what I have now in another branch for the time being, as I’m currently trying to wrap my head around the P2P network/Online Workspaces network service thing … Will get back to this after that.

**Comment by Luis-Fernando-Molina** [comment]
> Yes, 3 sounds good. Although it will still have the trade-off 2.b, right?

yes, it would not get the updates automatically, only after re running the the procedure to re-import all his indicators. Maybe that is a word we can use, IMPORT, meaning, extracting indicators from plugins and importing them into the workspace.

**Comment by Luis-Fernando-Molina** [comment]
> I guess I’ll park what I have now in another branch for the time being, as I’m currently trying to wrap my head around the P2P network/Online Workspaces network service thing … Will get back to this after that.

Good idea!

**Comment by BlaaSwe** [comment]
I agree with you @Luis-Fernando-Molina that point 3 makes most sense. 

Something to take into account is the references in the master trading mine
