### ISSUE TITLE
Mouse wheel not working well over scales for MAC OS users

### ISSUE THREAD

**Issue by Luis-Fernando-Molina** [Superalgos/Superalgos#385]
For some reason only detecting mouse wheel on one direction, when over the scales at MAC OS.

**Comment by CarnivalBen** [comment]
This happens on Windows as well when using Firefox.

**Comment by krisj** [comment]
I can second the above... latest Chrome on MAC OS, fresh install etc. Mouse wheel scrolling is nearly completely non-functioning in some areas. Sensitivity seems too low as well. It takes several vigorous scrolls to change up/down 1 fraction on scale widgets for example and Ctrl+Scroll does nothing in node editor.

**Comment by Luis-Fernando-Molina** [comment]
I am planning to fix this tomorrow, hopefully, at least on MAC

**Comment by Luis-Fernando-Molina** [comment]
Hey, just pushed a fix to develop addressing the usage of mouse wheel. I tested it in iOS / Safari only. Let me know if this fixed the issues you were seeing there.

**Comment by krisj** [comment]
@Luis-Fernando-Molina mouse wheel is still not working for me on Mac OS

**Comment by Luis-Fernando-Molina** [comment]
Can you please play a little bit with these two values, related to the sensitivity and come back to me with the ones that are perfect?
If you could manage to get the perfect tuning you can also submit a PR with the right values.

![image](https://user-images.githubusercontent.com/9479367/105361095-9e8da780-5bf9-11eb-8db8-50fd76585f6a.png)

**Comment by krisj** [comment]
Turns out you are using the native Chrome zoom functionality for this in the Design space and Node/Canvas method in Charting space - is that correct?
The problem is that on Mac version of Chrome there is no functionality to do native Chrome zoom with Ctrl+Mouse_Wheel (did a bit of research). I think you should just refactor/reengineer this to match the zooming with Charting space as zooming works there (I will play with the sensitivity settings and report back).

Finally tried SA on a PC with a powerful GPU - the experience is day and night! Tried it on another high spec Mac - unusable again.

So at this point would suggest that unless you guys can dramatically improve the overall performance and technicalities on Mac it should be noted as a Linux/PC only app in the GUI part for the time being. I've spent several days pulling my hair out to understand what I am doing wrong but it turns out that on Macs the UI just doesn't respond in a usable way. I can try on AMD/Nvidia macs when I get access to see if there is any difference.

**Comment by Luis-Fernando-Molina** [comment]
ok, I created this issue to add the native zoom feature for the Design Space one of these days.

https://github.com/Superalgos/Superalgos/issues/451

Sorry for the pain caused :-)
