### ISSUE TITLE
Unable to start Superalgos 1.2.x

### ISSUE THREAD

**Issue by wonder6oy** [Superalgos/Superalgos#3931]
Windows 11
Running normal and admin.
Both setup and portable versions.
I am unable to get past the welcome screen of any of the 1.2.x versions of Superalgos.
(It says "The UI is loading...")
I am able to access the menus, and can call up the Console Logs, which report (at the end) "Superalgos Platform App is Running!"
I can open it in my browser (same splash screen).

Version 1.1.x seems to be running fine however.

**Comment by harrellbm** [comment]
Have you run the setupPlugins script?

**Comment by wonder6oy** [comment]
Is that the .js file?  How do I install that?

**Comment by harrellbm** [comment]
> Is that the .js file?  How do I install that?

You can run it from the main directory but following these instructions from the Readme [Install Community Plugins](https://github.com/Superalgos/Superalgos/tree/develop#install-community-plugins)

**Comment by wonder6oy** [comment]
Ok - I figured out I needed to go through the entire Platform Client install process (for some reason I thought the .exe self contained install + dependencies would do it all - my mistake)
Brilliant program so far!

**Comment by BigJonMMXX** [comment]
the instructions say $ node setupPlugins <Your-Github-Username> <Your-Github-Token> -whats a github token ? (now TWO weeks and still havent got superalgos working)

**Comment by BigJonMMXX** [comment]
so now i've cloned/downloaded/synced ALL the plugins. And setup ALL of them. (not my idea of 'plugins' if they are all needed).

running again... and... (opens firefox every time...)... open chrome... and...
YEAH finally got to Welcome.

This project would be a lot more popular if there were some correct instructions on line to get it working.

missing: create a github token !!!
missing: you HAVE to clone/setup all plugins
missing: do NOT use the windows exe, its incomplete.

**Comment by wonder6oy** [comment]
"missing: you HAVE to clone/setup all plugins"

Ok.  I'll confess I've shelved SA for a time to try out some other things because of - issues.  This may be one of them.  Can you point me to a walkthrough on this?

**Comment by BigJonMMXX** [comment]
i am putting together a walkthrough - as its taken me days to get this
installed and running. i will publish soon...

**Comment by BigJonMMXX** [comment]
i've made a brief summary and posted it here...
https://forum.superalgos.org/t/windows-walkthrough-getting-started-summary
its just a reminder for me for next time i do a pc rebuild - hopefully it'll help others :)

**Comment by 9808us** [comment]
I read your post in the forum, very nice, it could help other users to get on board!
For sure the readme file can be updated and improved. 
I think that many issues come from all the stuff needed for the first time. 
What was your main problem with the install?
What is not clear in the readme file?

**Comment by BigJonMMXX** [comment]
Hi 9808us, 
i think the readme file is very informative - but those of us first arriving its just too much info - it takes too much effort and is demoralising. I had to go through it many times, wondering if parts were advisory or necessary, so many questions, again for noobs... example node.js - do we use defaults? others advise a few non-default settings! i couldnt find any up to date instructions... 
Maybe the readme could have a summary (like the one i did). obviously each step needs its own explanation - which i got their the respective sources. im not suggesting reinventing the wheel. But more clarificition would be great. example: plugins (which by definition are optional) are not optional for SA !! Github Token - again not optional but necessare) !! Windows exe, there's 3 options, with only an 'experts' comment - and then it turns out NONE of them are sufficient as more steps are needed (which have to be investigated, diagnosed, and discovered by the noob).
Again, i think its all great and i want to help - just saying, more people would come onboard it the start was easier...

**Comment by 9808us** [comment]
I forwarded your constructive comment to devs and see if we can improve instructions and make them a bit more clear. 
Thank you!

**Comment by julian-molina** [comment]
Hey @harrellbm... 

The guys here have pointed out some real hurdles that we can remove. Are you up for improving the README? It seems like we left a few things out after the last major reorg of the repositories. Things like getting the token from Github are covered in the Welcome tutorial, but after the reorg people need to know about that at an earlier stage. That seems to be the main issue.

Another idea would be to split the README so that we can have separate READMEs for each type of installation. The current file has got to truly overwhelming size and complexity.

@wonder6oy @BigJonMMXX thanks for pointing these issues out, and thanks for your patience. We're striving to make things easier to use, but the growth and ever-improving nature of the project makes it a bit of a challenge.

**Comment by julian-molina** [comment]
The README file has been fully revised and is available in the develop branch. Will be merged into master soon. This should solve all of the issues reported here involving unclear instructions on how to install the platform. I'm closing this issue, for the time being.
