### ISSUE TITLE
Minor Tips

### ISSUE THREAD

**Issue by BigJonMMXX** [Superalgos/Superalgos#3987]
A couple of minor points i'd like to contribute...

The interactive tutorials are great, thorough, detailed, pretty... but too much ! I've been through hours of them, but eventually just started clicking next, next, next.... And at the end of it all, i still dont know how to actually get the software up and running for a backtest situation of my specifications... MAybe its there and i missed it... you see my point.

Fonts !!! I can only assume the designer of the tutorials has the biggest monitor in the world - i spend every page zooming in and out. i just have a typical windows desktop setup, and some linux laptops - and on all its not optimal. When i got it all running on linux laptop, i thought i messed up as i couldnt see the Next, Skip buttons on the tutorial - didnt cross my mind for hours that it was just a zoom issue... (edit - worth pointing out, everytime i zoom the current tutorial disappears, and i have to press Previous and Next to see everything again, with my new zoom settings - this gets very tiresome very quick)

ON windows we start by RightClicking c:\gitrepos\superalgos -> git bash here -> type node platform --- is there away to create a desktop shortcut to do this ??

When SA starts up (previous point) it automatically open firefox, where sa doesnt work. i have Chrome, and use it, but im certainly not making it default just for one app - how do we change this ??

(just trying to help - thoughts from a noob)

**Comment by 9808us** [comment]
Hi, I'm currently rewriting the README file of SA.
Feel free to contribute, I would greatly appreciate!

https://github.com/9808us/SA-README

About the shortcut, it's explained in docs, just use 'node setup shortcut' and you should have it on your desktop.

https://github.com/9808us/SA-README#install-node-dependencies-and-community-plugins

About the browser, it's also explained in docs. Just copy/paste the address URL address from your default browser Firefox to whatever browser you would like to use. Once you copy the address then close Firefox because only one instance of SA con run at the same time (with default config).

https://github.com/9808us/SA-README#run-the-client-and-gui-using-the-command-line

**Comment by BigJonMMXX** [comment]
Thank you. i have discovered many of the workarounds, mainly through trial and error - which does take a lot of time. I did ask if it was possible to change the behaviour so i dont have to apply workarounds everytime. Like, opening Chrome by default (without altering the preferred settings of my desktop pc).

Also, you repeat "its explained in the docs" - and i repeat it doesnt work.
node setup shortcut ---- it says downloading external scripts... there are issues... run audit fix (that doesnt fix anything)...
And NO shortcuts are created.

$ npm audit fix
npm ERR! code 1
npm ERR! path D:\TecProjects\GitRepos\Superalgos\node_modules\electron
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node install.js
npm ERR! RequestError: CC260000:error:0A000119:SSL ro.........................

**Comment by BigJonMMXX** [comment]
And the new README is looking really good. Thanks.

**Comment by BigJonMMXX** [comment]
Here's a couple of other steps that tripped me up...
![1 tutorials](https://user-images.githubusercontent.com/74259098/161422417-303ea67c-abd1-4f2e-ac14-00dcc6ec0b33.PNG)
![2 tutorials](https://user-images.githubusercontent.com/74259098/161422440-eb848466-718e-4e6f-90f7-e49843cdded3.PNG)
![3 workspace](https://user-images.githubusercontent.com/74259098/161422453-9c06b310-5bd1-4947-8265-f929e127ecf6.PNG)

They might seem like nothing to experts, but for us noobs they are show stoppers.

**Comment by 9808us** [comment]
> Thank you. i have discovered many of the workarounds, mainly through trial and error - which does take a lot of time. I did ask if it was possible to change the behaviour so i dont have to apply workarounds everytime. Like, opening Chrome by default (without altering the preferred settings of my desktop pc).

It's not so easy to do that because we do not know where and how you install SA.
It could be linux, ubuntu, windows, mac, headless Raspberry ecc... so it could be a bit complex to to do what you ask ... and then what browser toi launch? Chrome? Edge? Brave? ... things start to complicate here.

That's why at the moment there is no oprtion for what you ask.

But feel free to explore FF and see if it works, I've never tested it with SA, personally I use Brave or Edge that are Chromium based like Chrome. Anyway it's just a matter of copy/paste the url or you can launch SA without the browser.

For example you can do this in your terminal in the SA main folder:

```sh
node platform noBrowser
```

This will run SA without opening any browser, then open the browser you prefer and use the URL localhost:34248. Try it!

**Comment by 9808us** [comment]
> Here's a couple of other steps that tripped me up... ![1 tutorials](https://user-images.githubusercontent.com/74259098/161422417-303ea67c-abd1-4f2e-ac14-00dcc6ec0b33.PNG) ![2 tutorials](https://user-images.githubusercontent.com/74259098/161422440-eb848466-718e-4e6f-90f7-e49843cdded3.PNG) ![3 workspace](https://user-images.githubusercontent.com/74259098/161422453-9c06b310-5bd1-4947-8265-f929e127ecf6.PNG)
> 
> They might seem like nothing to experts, but for us noobs they are show stoppers.

I will have a look at this in next days. Maybe some updates changed the design space.

**Comment by BigJonMMXX** [comment]
Thank you.
And editing the shortcut works well...
cmd /k "node platform minMemo noBrowser"
