### ISSUE TITLE
Close Stage Event not working on the Close Stage

### ISSUE THREAD

**Issue by bearwp** [Superalgos/Superalgos#829]
Windows 10
Latest Branch
Any workspace. Attached an example 
[Share - Trading System - .WHB v2.txt](https://github.com/Superalgos/Superalgos/files/6339464/Share.-.Trading.System.-.WHB.v2.txt)

Close Stage Event is attached to the Close Stage. However no condition in the event causes the stage to close.
![image](https://user-images.githubusercontent.com/37872826/115308519-bd50fb00-a162-11eb-998e-9b8c14851088.png)

Code reads `true`

**Comment by Luis-Fernando-Molina** [comment]
Gave you some hints on Telegram...

![image](https://user-images.githubusercontent.com/9479367/115915439-9f8dd980-a473-11eb-8bca-2e8186114fe1.png)

**Comment by Smidy13** [comment]
The Trading Session Functions file (Projects > Superalgos > UI > Functions-Library > TradingSessionsFunction.js) is used to build the JSON of each stage which is evaluated by the Trading Bot. However, it needs to be in the right order. The file had the "Close Stage Event" before the "Close Stage". I've reordered them so that the "Close Stage Event" is correctly after and a child of the "Close Stage".

Pull Request submitted to Develop Branch, here is the commit:
https://github.com/Superalgos/Superalgos/pull/835/commits/ebd1148e1f663587bb6d066367674b95e0f9f1b7

**Comment by Luis-Fernando-Molina** [comment]
![image](https://user-images.githubusercontent.com/9479367/115959808-56d72e80-a50e-11eb-99f1-736d7dd3d1b4.png)
